spring:
  application:
    name: profile-service

server:
  port: 9099

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://tk-be-discovery-service:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5