server:
  port: 9091

spring:
  application:
    name: profile-service
  management:
    security:
      enabled: false

#ENABLE DYNAMIC ROUTING
management:
  endpoints:
    routes:
      enabled: true
    web:
      exposure:
        include: "*"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5