server:
  port: 9091

spring:
  application:
    name: profile-service
#  management:
#    security:
#      enabled: false

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      auto-commit: false
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  cloud:
    loadbalancer:
      ribbon: 
        enabled: false

security:
  jwt:
    secret: 963D96C90030DD58429D2751AC1BDBBC
    
logging:
  file:
    name: /home/ubuntu/tk-be-profile-service.log
    
#ENABLE DYNAMIC ROUTING
management:
  endpoints:
    routes:
      enabled: true
    web:
      exposure:
        include: "*"

eureka:  
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    healthcheck:
      enabled: true
    lease:
      duration: 5
    register-with-eureka: true
    fetch-registry: true
    
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 600000 #10 mins
        readTimeout: 600000 #10 mins