spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      auto-commit: false
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    validateOnMigrate: false
    
security:
  jwt:
    secret: ${TOKEN_SECRET}

feign:
  hystrix:
    enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
    register-with-eureka: true
    fetch-registry: true